version: "1"
services:
    webapp:
        image: miniess
        container_name: miniess
        ports:
            - '8090:80'
        networks:
            - miniess-net
    esdb:
        image: eventstore/eventstore:21.10.1-buster-slim
        container_name: docker_esdb 
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        networks:
            - miniess-net
    
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        container_name: docker_sqlserver
        environment:
            SA_PASSWORD: "password_123"
            ACCEPT_EULA: "Y"
        networks:
            - miniess-net

networks:
    miniess-net:
        driver: bridge
