//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface GetTodoListsViewModel {
    todoLists: TodoList[];
}

export interface TodoList {
    streamId: string;
    title: string;
    todoItems: TodoItem[];
}

export interface TodoItem {
    id: number;
    isCompleted: boolean;
    description: string;
}

export interface GetTodoListViewModel {
    todoList: TodoList;
}

export interface AddTodoListResponseModel {
    createdTodoListId: string;
}

export interface AddTodoListInputModel {
    title: string;
}

export interface AddTodoItemResponseModel {
    todoListId: string;
    createdTodoItemId: number;
}

export interface AddTodoItemInputModel {
    todoListId: string;
    description: string;
}

export interface CompleteTodoItemResponseModel {
    todoListId: string;
    todoItemId: number;
}

export interface CompleteTodoItemInputModel {
    todoListId: string;
    todoItemId: number;
}

export interface WeatherForecast {
    date: Date;
    temperatureC: number;
    temperatureF: number;
    summary: string;
}